---
# General config.
gitlab_external_url: "https://{{ gitlab_host }}"
gitlab_registry_external_host: "{{ registry_host }}"

# SSL Configuration.
gitlab_redirect_http_to_https: "true"

gitlab_ssl_certificate: "/etc/gitlab/ssl/{{ gitlab_host }}.crt"
gitlab_ssl_certificate_key: "/etc/gitlab/ssl/{{ gitlab_host }}.key"

gitlab_registry_ssl_certificate: "/etc/gitlab/ssl/{{ registry_host }}.crt"
gitlab_registry_ssl_certificate_key: "/etc/gitlab/ssl/{{ registry_host }}.key"

# SSL Self-signed Certificate Configuration.
gitlab_create_self_signed_cert: true
gitlab_self_signed_cert_subj: "/C=US/ST=Missouri/L=Saint Louis/O=IT/CN={{ gitlab_host }}"

# Probably best to leave this as the default, unless doing testing.
gitlab_restart_handler_failed_when: 'gitlab_restart.rc != 0'

# Optional settings.
gitlab_time_zone: "UTC"
gitlab_backup_keep_time: "604800"

# Email configuration.
gitlab_email_enabled: "true"
gitlab_email_from: "gitlab@{{ gitlab_host }}"
gitlab_email_display_name: "Gitlab"
gitlab_email_reply_to: "gitlab@{{ gitlab_host }}"